// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgbrkcK6VCCGXhV107SjHydYKh2R20Jis',
    appId: '1:116865250696:web:650ccaa653ce898726b63d',
    messagingSenderId: '116865250696',
    projectId: 'smart-budget-56729',
    authDomain: 'smart-budget-56729.firebaseapp.com',
    storageBucket: 'smart-budget-56729.firebasestorage.app',
    measurementId: 'G-MB1KZWZYWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCipPzKsyOCiRw1RRwFlY6A8H3k0yc7mPQ',
    appId: '1:116865250696:android:a664c245a39d9c7b26b63d',
    messagingSenderId: '116865250696',
    projectId: 'smart-budget-56729',
    storageBucket: 'smart-budget-56729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyK6jGP1JNrkkmJNo7aQnih5xUAmSbIeQ',
    appId: '1:116865250696:ios:b2b046ff8ba11d9d26b63d',
    messagingSenderId: '116865250696',
    projectId: 'smart-budget-56729',
    storageBucket: 'smart-budget-56729.firebasestorage.app',
    iosBundleId: 'com.millie.smartbudget.smartbudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyK6jGP1JNrkkmJNo7aQnih5xUAmSbIeQ',
    appId: '1:116865250696:ios:b2b046ff8ba11d9d26b63d',
    messagingSenderId: '116865250696',
    projectId: 'smart-budget-56729',
    storageBucket: 'smart-budget-56729.firebasestorage.app',
    iosBundleId: 'com.millie.smartbudget.smartbudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgbrkcK6VCCGXhV107SjHydYKh2R20Jis',
    appId: '1:116865250696:web:bdda44a79fd58d3e26b63d',
    messagingSenderId: '116865250696',
    projectId: 'smart-budget-56729',
    authDomain: 'smart-budget-56729.firebaseapp.com',
    storageBucket: 'smart-budget-56729.firebasestorage.app',
    measurementId: 'G-JMCE91VSTT',
  );
}
