import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart'; // ✅ Firebase core
// import 'package:smartbudget/views/parents/parent_dashboard_screen.dart';
import 'firebase_options.dart'; // ✅ Generated by flutterfire configure

import 'controllers/auth_controller.dart';
import 'controllers/budget_controller.dart';
import 'controllers/transaction_controller.dart';
import 'controllers/theme_controller.dart';

import 'views/auth/login_screen.dart';
import 'views/auth/register_screen.dart';
import 'views/student/budget_setup_screen.dart';
import 'views/student/transaction_entry_screen.dart';
import 'views/student/dashboard_screen.dart';
import 'views/parents/parent_dashboard_screen.dart';

import 'utils/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // ✅ Required before Firebase init
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const SmartBudgetApp());
}

class SmartBudgetApp extends StatelessWidget {
  const SmartBudgetApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthController()),
        ChangeNotifierProvider(create: (_) => BudgetController()),
        ChangeNotifierProvider(create: (_) => TransactionController()),
        ChangeNotifierProvider(create: (_) => ThemeController()),
      ],
      child: Consumer<ThemeController>(
        builder: (context, themeController, child) {
          return MaterialApp(
            title: 'Smart Budget',
            debugShowCheckedModeBanner: false,
            theme: AppTheme.lightTheme,
            darkTheme: AppTheme.darkTheme,
            themeMode: themeController.themeMode,
            home: const LoginScreen(), // 🔐 Firebase login will go here
            routes: {
              '/login': (context) => const LoginScreen(),
              '/register': (context) => const RegisterScreen(),
              '/student_dashboard': (context) => const StudentDashboardScreen(),
              '/budget-setup': (context) => const BudgetSetupScreen(),
              '/transaction-entry': (context) => const TransactionEntryScreen(),
              '/dashboard': (context) => const StudentDashboardScreen(),
              '/parent_dashboard': (context) => const ParentDashboardScreen(),
            },
          );
        },
      ),
    );
  }
}
